---

brew_taps:
    - homebrew/cask-fonts                                           # needed for font-*
    #- jakehilborn/jakehilborn                                      # needed for displayplacer

brew_packages:
    - coreutils                                                     # GNU File, Shell, and Text utilities
    - binutils                                                      # FSF Binutils for native development
    - diffutils                                                     # File comparison utilities
    - findutils                                                     # GNU find, xargs, and locate
    - gawk
    - grep
    #- ack                                                          # Search tool like grep, but optimized for programmers
    #- ag                                                           # Code-search similar to ack
    - less
    - gnu-sed
    - gnu-which
    - gnu-indent
    - gnu-getopt

    - jq                                                            # Lightweight and flexible command-line JSON processor
    - pv                                                            # Monitor data's progress through a pipe
    - utf8proc                                                      # Clean C library for processing UTF-8 Unicode data

    - gnu-tar
    - unzip
    - gzip
    - pigz                                                          # Parallel gzip
    - xz                                                            # General-purpose data compression with high compression ratio
    - p7zip                                                         # 7-Zip (high compression file archiver) implementation
    - brotli                                                        # Generic-purpose lossless compression algorithm by Google https://github.com/google/brotli

    - bash
    #- zsh                                                          Installed via seperate role
    - fish

    - screen
    - z                                                             # Tracks most-used directories to make cd smarter
    #- fasd                                                         # quick access to files and directories https://github.com/clvv/fasd
    - diff-so-fancy                                                 # Good-lookin' diffs with diff-highlight and more
    - grc                                                           # Colorize logfiles and command output
    - midnight-commander                                                            # Midnight commander
    - rename
    - hugo
    - grip                                                          # Github markdown preview

    - ipcalc                                                        # Calculate various network masks
    - netcat                                                        # Utility for managing network connections
    - nmap                                                          # Port scanning utility for large networks
    - rsync
    - curl
    - httpie                                                        # User-friendly cURL replacement (command-line HTTP client)    - wget --with-iri                                               # Internet file retriever
    - lynx                                                          # Text-based web browser
    - httrack                                                       # Website copier/offline browser
    #- iperf
    - iperf3
    #- bind
    #- dnsmasq
    #- unbound

    - gnutls                                                        # GNU TLS
    - gnupg
    - openssl                                                       # SSL/TLS cryptography library
    - ssh-copy-id                                                   # Copy identy to authorized keys of remote maschine
    - pwgen                                                         # Password generator
    - testssl                                                       # Tool which checks for the support of TLS/SSL ciphers and flaws

    - watch                                                         # Executes a program periodically, showing output fullscreen
    - htop                                                          # Improved top (interactive process viewer)
    - tree                                                          # Display directories as trees

    #- gd                                                           # Graphics library to dynamically manipulate images
    #- imagemagick                                                  # Tools and libraries to manipulate images in many formats
    #- ghostscript                                                  # Interpreter for PostScript and PDF
    #- exiftool
    #- pandoc                                                       # Convert markup format
    #- graphviz
    #- ffmpeg
    #- x264
    #- xvid
    #- lame
    #- webp

    - git
    #- git-flow
    #- git-extras
    - asdf
    - packer

    # Automation
    - ansible
    #- terraform
    #- terragrunt

    # AWS
    - awscli
    - awsume

    # Go
    - go

    # JavaScript
    - nvm
    - node
    - yarn

    # Ruby
    #- rbenv
    #- ruby
    #- ruby-build

    # Java
    #- ant
    #- maven
    #- groovy

    # Scala
    #- sbt
    #- scala
    #- apache-spark

    #- sqlite
    #- postgresql
    #- mongodb

    #- openldap                                                     # CLI LDAP tool
    #- tesseract                                                    # OCR (Optical Character Recognition) engine

brew_cask_packages:
    #- avira-antivirus
    - keepassx
    #- osxfuse
    - veracrypt
    #- cryptomator
    - rectangle                                                     # Resize OS X windows https://github.com/rxhanson/Rectangle replaces spectacle
    #- displayplacer                                                 # Arrange OS X screens https://github.com/jakehilborn/displayplacer --> depends on jakehilborn/jakehilborn
    #- iglance                                                       # Status bar system info for OS X https://github.com/iglance/iGlance
    #- istat-menus
    - caffeine                                                      # Prevent your Mac from automatically going to sleep https://intelliscapesolutions.com/apps/caffeine
    - aldente                                                       # Battery management https://apphousekitchen.com
    - sound-control                                                 # Sound output management https://staticz.com/soundcontrol/
    #- bluesnooze                                                   # Sleeping Mac = Bluetooth off https://github.com/odlp/bluesnooze

    - google-chrome
    - firefox

    - font-fira-code                                                # Fira Code enables font ligatures for example != https://github.com/tonsky/FiraCode
    #- font-iosevka                                                  # Possible replacement for Fira https://github.com/be5invis/Iosevka
    - visual-studio-code                                            # Configured in separate role
    - sourcetree
    #- meld
    - postman
    - insomnia
    - hex-fiend
    #- jetbrains-toolbox
    #- folx
    #- unetbootin
    #- balenaetcher

    #- wireshark
    #- wireshark-chmodbpf
    - charles                                                       # HTTP proxy https://www.charlesproxy.com
    #- mono-mdk                                                     # Needed by fiddler
    #- fiddler
    #- filezilla
    #- cyberduck
    #- tunnelblick

    #- dropbox
    - google-drive                                                  # Replaces google-backup-and-sync which is no longer supported
    #- rescuetime
    #- tomighty                                                     # No longer used and replaced with next
    - tomatobar                                                     # Pomodoro timer
    - teamviewer

    #- rambox
    #- skype
    #- zoom
    - signal

    #- xmind
    - freemind
    #- adobe-acrobat-reader
    #- boostnote
    - joplin
    - microsoft-auto-update
    - microsoft-office
    #- portfolioperformance
    - banking-4

    #- balsamiq-mockups
    - imageoptim
    - gimp
    #- krita
    - rar
    #- pencil
    #- xquartz
    #- inkscape
    #- scribus
    #- freecad
    #- vlc                                                          Installed via seperate role
    #- elmedia-player                                               Better VLC alternative
    - spotify
    #- handbrake
    #- obs                                                           # Screen capturing https://obsproject.com/ driver needed https://obsproject.com/forum/threads/how-to-capture-desktop-audio-on-mac.16491/
    - calibre                                                        # E-Book manager https://calibre-ebook.com
    - anki
    #- gmvault

    #- origami-studio
    #- google-web-designer

    # Kubernetes (K8s)
    #- kubernetes-cli                                                # CLI for Kubernetes
    #- kubectx                                                       # Tool that can switch between kubectl contexts easily and create aliases
    #- k9s                                                           # Monitor K8s cluster in CLI
    #- openlens                                                      # Monitor K8s cluster in an app
    #- fzf                                                           # Fuzzy finder for CLI
    #- mkcert                                                        # Local development TLS helper https://github.com/FiloSottile/mkcert
    #- testssl                                                       # SSL test tool https://testssl.sh/

    # Virtualisation
    - docker
    #- docker-completion
    #- podman
    #- podman-desktop
    #- rancher
    #- kind
    #- kitematic
    #- vagrant
    #- vagrant-manager
    #- virtualbox
    #- virtualbox-extension-pack

    # Java
    #- netbeans
    #- java
    #- java8
    #- jce-unlimited-strength-policy8

    # Haskell
    #- haskell-platform

    # Android
    #- android-file-transfer
    #- android-sdk
    #- android-studio

    # Database
    #- dbeaver-community
    #- mysqlworkbench
    #- postico
    #- sequel-pro
    #- apache-directory-studio                                       # LDAP GUI http://directory.apache.org/studio
    #- mongodb-compass

    # GIS
    #- qgis

    # Games
    #- openttd
    #- openra
