---

brew_taps:
    - caskroom/cask                                                 # Needed for binary packages
    - homebrew/science                                              # Needed for OpenCV

brew_packages:
    - coreutils                                                     # GNU File, Shell, and Text utilities
    - binutils                                                      # FSF Binutils for native development
    - diffutils                                                     # File comparison utilities
    - { name: findutils, install_options: "--default-names" }       # GNU find, xargs, and locate
    - { name: gnu-sed, install_options: "--default-names" }
    - gawk
    - { name: grep, install_options: "--default-names" }
    #- ack                                                          # Search tool like grep, but optimized for programmers
    #- ag                                                           # Code-search similar to ack
    - less
    - { name: gnu-which, install_options: "--default-names" }

    - jq                                                            # Lightweight and flexible command-line JSON processor
    - pv                                                            # Monitor data's progress through a pipe
    - utf8proc                                                      # Clean C library for processing UTF-8 Unicode data

    - { name: gnu-tar, install_options: "--default-names" }
    - unrar
    - unzip
    - gzip
    - pigz                                                          # Parallel gzip
    - xz                                                            # General-purpose data compression with high compression ratio
    - p7zip                                                         # 7-Zip (high compression file archiver) implementation

    - bash
    - zsh
    #- zsh-syntax-highlighting                                      # Red/Green command checker - Now cloned in zsh_oh-my-zsh
    #- zsh-autosuggestions                                          # History of commands - Now cloned in zsh_oh-my-zsh
    - fish

    - screen
    - z                                                             # Tracks most-used directories to make cd smarter
    #- fasd                                                         # quick access to files and directories https://github.com/clvv/fasd
    - diff-so-fancy                                                 # Good-lookin' diffs with diff-highlight and more
    - grc                                                           # Colorize logfiles and command output
    - mc                                                            # Midnight commander
    - rename
    - hugo
    - grip                                                          # Github markdown preview

    - ipcalc                                                        # Calculate various network masks
    - netcat                                                        # Utility for managing network connections
    - nmap                                                          # Port scanning utility for large networks
    - rsync
    - curl
    - httpie                                                        # User-friendly cURL replacement (command-line HTTP client)    - wget --with-iri                                               # Internet file retriever
    - lynx                                                          # Text-based web browser
    #- iperf
    - iperf3

    - { name: gnutls, install_options: "--default-names" }          # GNU TLS
    - gnupg
    - gpg-agent
    - openssl                                                       # SSL/TLS cryptography library
    - ssh-copy-id                                                   # Copy identy to authorized keys of remote maschine
    - pwgen                                                         # Password generator
    - testssl                                                       # Tool which checks for the support of TLS/SSL ciphers and flaws

    - watch                                                         # Executes a program periodically, showing output fullscreen
    - htop                                                          # Improved top (interactive process viewer)
    - tree                                                          # Display directories as trees

    #- gd                                                           # Graphics library to dynamically manipulate images
    #- imagemagick                                                  # Tools and libraries to manipulate images in many formats
    #- ghostscript                                                  # Interpreter for PostScript and PDF
    #- exiftool
    #- pandoc                                                       # Convert markup format
    #- graphviz
    #- ffmpeg
    #- x264
    #- xvid
    #- lame
    #- webp

    - git
    - git-flow
    #- git-extras
    - packer

    #- docker-completion

    - ansible
    - nvm
    - node
    - yarn
    #- go
    #- rbenv
    #- ruby
    #- ruby-build
    #- ant
    #- maven
    #- groovy
    #- sbt
    #- scala
    #- apache-spark

    #- sqlite
    #- postgresql
    #- mongodb

brew_cask_packages:
    - avast-security
    - keepassx
    - osxfuse
    - veracrypt
    #- cryptomator
    - spectacle                                                     # Resize OS X windows https://www.spectacleapp.com

    - google-chrome
    - firefox

    - visual-studio-code
    #- netbeans
    - sourcetree
    - meld
    #- apache-directory-studio                                       # LDAP GUI http://directory.apache.org/studio
    #- mysqlworkbench
    #- postico
    #- sequel-pro
    #- mongodb-compass
    - postman

    - wireshark
    - charles                                                       # HTTP proxy https://www.charlesproxy.com
    - mono-mdk                                                      # Needed by fiddler
    - fiddler
    #- filezilla
    #- cyberduck

    - dropbox
    - rescuetime
    - tomighty
    - teamviewer
    - skype

    #- xmind
    - freemind
    - adobe-acrobat-reader
    #- boostnote

    - imageoptim
    - gimp
    #- krita
    - pencil
    - xquartz
    - inkscape
    #- scribus
    #- freecad
    - vlc
    - calibre                                                       # E-Book manager https://calibre-ebook.com
    - anki
    #- gmvault

    #- origami-studio
    #- google-web-designer

    - java
    #- jce-unlimited-strength-policy8
    #- haskell-platform
    #- unetbootin

    - docker
    #- kitematic
    - vagrant
    - vagrant-manager
    - virtualbox
    #- virtualbox-extension-pack

    - android-file-transfer
    #- android-sdk
    #- android-studio

    #- openttd
