---

brew_taps: []

brew_packages:
    - coreutils                                                     # GNU File, Shell, and Text utilities
    - binutils                                                      # FSF Binutils for native development
    - diffutils                                                     # File comparison utilities
    - findutils                                                     # GNU find, xargs, and locate
    - gnu-sed
    - gawk
    - grep
    #- ack                                                          # Search tool like grep, but optimized for programmers
    #- ag                                                           # Code-search similar to ack
    - less
    - gnu-which
    - gnu-indent
    - gnu-getopt

    - jq                                                            # Lightweight and flexible command-line JSON processor
    - pv                                                            # Monitor data's progress through a pipe
    - utf8proc                                                      # Clean C library for processing UTF-8 Unicode data

    - gnu-tar
    - unrar
    - unzip
    - gzip
    - pigz                                                          # Parallel gzip
    - xz                                                            # General-purpose data compression with high compression ratio
    - p7zip                                                         # 7-Zip (high compression file archiver) implementation

    - bash
    - zsh
    #- zsh-syntax-highlighting                                      # Red/Green command checker - Now cloned in zsh_oh-my-zsh
    #- zsh-autosuggestions                                          # History of commands - Now cloned in zsh_oh-my-zsh
    - fish

    - screen
    - z                                                             # Tracks most-used directories to make cd smarter
    #- fasd                                                         # quick access to files and directories https://github.com/clvv/fasd
    - diff-so-fancy                                                 # Good-lookin' diffs with diff-highlight and more
    - grc                                                           # Colorize logfiles and command output
    - mc                                                            # Midnight commander
    - rename
    - hugo
    - grip                                                          # Github markdown preview

    - ipcalc                                                        # Calculate various network masks
    - netcat                                                        # Utility for managing network connections
    - nmap                                                          # Port scanning utility for large networks
    - rsync
    - curl
    - httpie                                                        # User-friendly cURL replacement (command-line HTTP client)    - wget --with-iri                                               # Internet file retriever
    - lynx                                                          # Text-based web browser
    #- iperf
    - iperf3
    - bind

    - gnutls                                                        # GNU TLS
    - gnupg
    - openssl                                                       # SSL/TLS cryptography library
    - ssh-copy-id                                                   # Copy identy to authorized keys of remote maschine
    - pwgen                                                         # Password generator
    - testssl                                                       # Tool which checks for the support of TLS/SSL ciphers and flaws

    - watch                                                         # Executes a program periodically, showing output fullscreen
    - htop                                                          # Improved top (interactive process viewer)
    - tree                                                          # Display directories as trees

    #- gd                                                           # Graphics library to dynamically manipulate images
    #- imagemagick                                                  # Tools and libraries to manipulate images in many formats
    #- ghostscript                                                  # Interpreter for PostScript and PDF
    #- exiftool
    #- pandoc                                                       # Convert markup format
    #- graphviz
    #- ffmpeg
    #- x264
    #- xvid
    #- lame
    #- webp

    - git
    - git-flow
    #- git-extras
    - packer

    #- docker-completion

    - ansible
    - nvm
    - node
    - yarn
    #- go
    #- rbenv
    #- ruby
    #- ruby-build
    #- ant
    #- maven
    #- groovy
    #- sbt
    #- scala
    #- apache-spark

    #- sqlite
    #- postgresql
    #- mongodb

brew_cask_packages:
    - avast-security
    - keepassx
    - osxfuse
    - veracrypt
    #- cryptomator
    - spectacle                                                     # Resize OS X windows https://www.spectacleapp.com

    - google-chrome
    - firefox

    - visual-studio-code
    - sourcetree
    - meld
    - postman
    - hex-fiend
    - jetbrains-toolbox
    #- folx
    #- unetbootin

    - wireshark
    - charles                                                       # HTTP proxy https://www.charlesproxy.com
    #- mono-mdk                                                     # Needed by fiddler
    #- fiddler
    #- filezilla
    #- cyberduck
    - tunnelblick

    - dropbox
    - google-backup-and-sync
    #- rescuetime
    - tomighty
    - teamviewer

    - rambox
    - signal

    #- xmind
    - freemind
    #- adobe-acrobat-reader
    #- boostnote
    - microsoft-office
    - fujitsu-scansnap-manager-ix500

    - imageoptim
    - gimp
    #- krita
    #- pencil
    #- xquartz
    #- inkscape
    #- scribus
    #- freecad
    - vlc
    - handbrake
    - calibre                                                       # E-Book manager https://calibre-ebook.com
    - anki
    #- gmvault

    #- origami-studio
    #- google-web-designer

    # Virtualisation
    - docker
    #- kitematic
    #- vagrant
    #- vagrant-manager
    #- virtualbox
    #- virtualbox-extension-pack

    # Java
    #- netbeans
    #- java
    #- java8
    #- jce-unlimited-strength-policy8

    # Haskell
    #- haskell-platform

    # Android
    #- android-file-transfer
    #- android-sdk
    #- android-studio

    # Database
    #- dbeaver-community
    #- mysqlworkbench
    #- postico
    #- sequel-pro
    #- apache-directory-studio                                       # LDAP GUI http://directory.apache.org/studio
    #- mongodb-compass

    # Games
    #- openttd
